variable "aws_region" { type = string
  default = "us-east-1" }
variable "project" { type = string
  default = "genai-observability" }
variable "candidate_model_id" { type = string
  description = "Bedrock Converse-compatible model/inference profile for the production app" }
variable "oracle_model_id_a" { type = string
  description = "First Bedrock oracle model/inference profile" }
variable "oracle_model_id_b" { type = string
  description = "Second Bedrock oracle model/inference profile (may equal A)" }
variable "replay_model_id" { type = string
  description = "Default Bedrock replay model" }
variable "honeycomb_api_key_secret_arn" { type = string
  description = "Secrets Manager ARN whose secret value is the Honeycomb API key" }
variable "honeycomb_otlp_endpoint" { type = string
  default = "https://api.honeycomb.io" }
variable "app_image_tag" { type = string
  default = "latest" }
variable "desired_count" { type = number
  default = 1 }
variable "enable_deletion_protection" { type = bool
  default = false }
